import 'dart:io';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_module/widgets/auth/auth_form.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/services.dart';

class AuthScreen extends StatefulWidget {
  @override
  _AuthScreenState createState() => _AuthScreenState();
}

class _AuthScreenState extends State<AuthScreen> {
  final _auth = FirebaseAuth.instance;
  var _isLoading = false;

  void _submitAuthForm(
    String email,
    String password,
    String userName,
    File image,
    bool isLogin,
    BuildContext ctx,
  ) async {
    AuthResult authResult;
    try {
      setState(() {
        _isLoading = true;
      });
      if (isLogin) {
        authResult = await _auth.signInWithEmailAndPassword(
          email: email,
          password: password,
        );
      } else {
        authResult = await _auth.createUserWithEmailAndPassword(
          email: email,
          password: password,
        );

        // UPLOAD THE USER IMAGE
        // REF POINTS AT THE FIREBASE STORAGE MAIN "BUCKET" (MAIN PATH TO STORE DATA)
        // CHILD GIVES ACCESS TO A CERTAIN PATH IN THE BUCKET (THEY'RE LIKE FOLDERS)
        // IMAGES TAKEN BY THE PHONE'S CAMERA ARE GENERALLY .JPG
        final ref = FirebaseStorage.instance
            .ref()
            .child('user_image')
            .child(authResult.user.uid + '.jpg');
        // ONCOMPLETE GIVES A FUTURE TO INDICATE THAT THE PUTFILE METHOD COMPLETED
        await ref.putFile(image).onComplete;

        // CREATE A COLLECTION USERS IF IT DOESN'T EXIST
        // THEN CREATE A NEW DOCUMENT WITH THE ID GENERATED BY FIREBASE AUTH SERVICE
        await Firestore.instance
            .collection('/users')
            .document(authResult.user.uid)
            .setData(
          // INSERTS DATA IN THE DOCUMENT
          {'username': userName, 'email': email},
        );
      }
      // PlatformException CATCHES ERRORS THREW BY FIREBASE
    } on PlatformException catch (err) {
      var message = 'An error occurred, please check your credentials';
      if (err.message != null) {
        message = err.message;
      }
      Scaffold.of(ctx).showSnackBar(
        SnackBar(
          content: Text(message),
          backgroundColor: Theme.of(ctx).errorColor,
        ),
      );
      setState(() {
        _isLoading = false;
      });
      // CATCHES ANY OTHER ERRORS THAT COULD BE THROWN
    } catch (err) {
      print(err);
      setState(() {
        _isLoading = true;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).primaryColor,
      body: AuthForm(_submitAuthForm, _isLoading),
    );
  }
}
