import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_module/widgets/auth/auth_form.dart';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/services.dart';

class AuthScreen extends StatefulWidget {
  @override
  _AuthScreenState createState() => _AuthScreenState();
}

class _AuthScreenState extends State<AuthScreen> {
  final _auth = FirebaseAuth.instance;
  var _isLoading = false;

  void _submitAuthForm(
    String email,
    String password,
    String userName,
    bool isLogin,
    BuildContext ctx,
  ) async {
    AuthResult authResult;
    try {
      setState(() {
        _isLoading = true;
      });
      if (isLogin) {
        authResult = await _auth.signInWithEmailAndPassword(
          email: email,
          password: password,
        );
      } else {
        authResult = await _auth.createUserWithEmailAndPassword(
          email: email,
          password: password,
        );
        // CREATE A COLLECTION USERS IF IT DOESN'T EXIST
        // THEN CREATE A NEW DOCUMENT WITH THE ID GENERATED BY FIREBASE AUTH SERVICE
        await Firestore.instance
            .collection('/users')
            .document(authResult.user.uid)
            .setData(
          // INSERTS DATA IN THE DOCUMENT
          {'username': userName, 'email': email},
        );
      }
      // PlatformException CATCHES ERRORS THREW BY FIREBASE
    } on PlatformException catch (err) {
      var message = 'An error occurred, please check your credentials';
      if (err.message != null) {
        message = err.message;
      }
      Scaffold.of(ctx).showSnackBar(
        SnackBar(
          content: Text(message),
          backgroundColor: Theme.of(ctx).errorColor,
        ),
      );
      setState(() {
        _isLoading = false;
      });
      // CATCHES ANY OTHER ERRORS THAT COULD BE THROWN
    } catch (err) {
      print(err);
      setState(() {
        _isLoading = true;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).primaryColor,
      body: AuthForm(_submitAuthForm, _isLoading),
    );
  }
}
